version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

      - run: yarn build

  deploy:
    executor: my-executor

    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - "b3:88:6d:5a:46:55:5a:26:8f:8f:5f:55:dd:38:0c:7f"
      - run:
          name: Deploy Over SSH
          command: |
            ls -all
            pwd

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
